apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "paperless-ngx.postgresql.clusterName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  instances: {{ .Values.postgresql.instances }}
  imageName: {{ .Values.postgresql.imageName }}

  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database }}
      owner: {{ .Values.postgresql.owner }}
      {{- if .Values.postgresql.existingSecret.name }}
      secret:
        name: {{ .Values.postgresql.existingSecret.name }}
      {{- end }}

  storage:
    size: {{ .Values.postgresql.storage.size }}
    {{- if .Values.postgresql.storage.storageClass }}
    storageClassName: {{ .Values.postgresql.storage.storageClass }}
    {{- end }}

  {{- with .Values.postgresql.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
