{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.tika.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: tika
spec:
  type: {{ .Values.tika.service.type }}
  ports:
    - port: {{ .Values.tika.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tika
{{- end }}
